#!/usr/bin/env python3
"""Generate the dialect_corpus_sentences seed migration from the Lisan sample.

Reads docs/yemeni/sentences-sample.jsonl and writes
supabase/migrations/20260804140000_seed_yemeni_corpus_sentences.sql.

Generated rather than hand-written so the SQL and the JSONL cannot drift, and
so re-running the derivation upstream is a one-command refresh. Rerunning is
safe: the migration is idempotent via ON CONFLICT DO NOTHING against the
(dialect, md5(text)) unique index.

Every row seeds with `vetted` NULL, which is inert -- buildCorpus reads
`vetted = true` only. `keyword_flagged` records a cheap pre-pass so the model
vetting pass can skip obvious rejects instead of paying to classify them. It is
NOT the gate: keyword filtering was measured against this very sample and 38% of
the sentences it called non-political still hit an extended slur list.

Usage:  python3 scripts/generate-corpus-seed.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'docs/yemeni/sentences-sample.jsonl'
OUT = ROOT / 'supabase/migrations/20260804140000_seed_yemeni_corpus_sentences.sql'

# Extends the derivation's own 18-term list with what hand-reading its output
# turned up. عفاش is kept short on purpose: it is not a substring of العفافيش,
# which is precisely how that slur reached the sample marked clean.
EXTRA_TERMS = [
    'حوث', 'عفاش', 'عفافيش', 'دحباش', 'دنبوع', 'زينبي', 'مليشيا', 'مرتزق',
    'خائن', 'خون', 'عميل', 'ضالعي', 'كافر',
    'قصف', 'صاروخ', 'شهيد', 'ارهاب', 'اغتيال', 'مقبره', 'جبهه', 'جبهات',
    'انفصال', 'تحرير', 'محرر', 'دماء',
    'معفن', 'وصخ', 'قبحك', 'لعنه', 'حشيش',
]

TASHKEEL = re.compile(r'[ً-ٰٟـ]')


def norm(s: str) -> str:
    s = TASHKEEL.sub('', s or '')
    s = re.sub(r'[آأإ]', 'ا', s)
    return s.replace('ى', 'ي').replace('ة', 'ه')


TERMS = [norm(t) for t in EXTRA_TERMS]
LATIN_RUN = re.compile(r'[A-Za-z]{3}')


def flagged(row: dict) -> bool:
    if row.get('political'):
        return True
    text = norm(row.get('text_clean') or row.get('text') or '')
    if any(t in text for t in TERMS):
        return True
    # Not a safety concern, but mojibake and latin runs are useless for mining
    # and would waste a classification call.
    if '?' in text or LATIN_RUN.search(text):
        return True
    return False


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    if not SRC.exists():
        sys.exit(f'missing {SRC}')

    rows, seen = [], set()
    for line in SRC.read_text(encoding='utf-8').splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        text = (r.get('text_clean') or r.get('text') or '').strip()
        if not text:
            continue
        key = norm(text)
        if key in seen:            # the unique index would reject these anyway
            continue
        seen.add(key)
        rows.append((text, r.get('token_count'), flagged(r)))

    n_flagged = sum(1 for _, _, f in rows if f)
    header = f"""-- Seed the Yemeni corpus sentence pool from the Lisan sample.
--
-- GENERATED by scripts/generate-corpus-seed.py from
-- docs/yemeni/sentences-sample.jsonl. Do not hand-edit; regenerate instead.
--
-- {len(rows)} sentences, of which {n_flagged} are keyword_flagged
-- ({n_flagged / len(rows):.0%}) and will be auto-rejected by the vetting pass
-- without spending a model call.
--
-- Every row seeds with `vetted` NULL, which is INERT: buildCorpus reads
-- `vetted = true` only, so this migration changes no generated content. The
-- vet-corpus-sentences edge function judges them; see
-- 20260804130000_dialect_corpus_sentences.sql for why keyword filtering is a
-- cost optimisation here and not the gate.
--
-- Source: Lisan Yemeni corpus, Jarrar et al. 2022, CC BY 4.0. Attribution is
-- carried per row in the `license` column.

INSERT INTO public.dialect_corpus_sentences
  (dialect, text, token_count, source, license, keyword_flagged)
VALUES
"""

    values = ",\n".join(
        f"  ('Yemeni', {sql_str(t)}, {tc if isinstance(tc, int) else 'NULL'},"
        f" 'lisan', 'CC BY 4.0', {str(f).lower()})"
        for t, tc, f in rows
    )

    OUT.write_text(header + values + "\nON CONFLICT DO NOTHING;\n", encoding='utf-8')
    size_kb = OUT.stat().st_size / 1024
    print(f'wrote {OUT.relative_to(ROOT)}: {len(rows)} rows, {n_flagged} flagged, {size_kb:.0f} KB')
    return 0


if __name__ == '__main__':
    sys.exit(main())
