-- Per-learner mnemonic for curriculum cards.
--
-- `user_vocabulary` and `user_phrases` have carried a `mnemonic` column for a
-- while, and LeechHelperPanel writes one when a card keeps failing. The
-- curriculum deck — the structured material every learner actually works
-- through — had no equivalent, so a learner grinding a curriculum word into the
-- ground for the seventh time got no rescue at all: no mnemonic, no flag, no
-- way to reset the count. The two decks a learner builds themselves got all
-- three; the deck the app hands them got none.
--
-- It goes on word_reviews rather than vocabulary_words because a mnemonic is a
-- personal memory hook, not content: "sounds like the English word my brother
-- always says" helps exactly one person. vocabulary_words is shared across every
-- learner, so a mnemonic there would either leak one learner's associations to
-- everyone or need a whole new join table to avoid it. word_reviews is already
-- the per-user row for a curriculum word, and 20260726110000 established it as
-- the place the learner's own SRS state lives.

ALTER TABLE public.word_reviews
  ADD COLUMN IF NOT EXISTS mnemonic text;

COMMENT ON COLUMN public.word_reviews.mnemonic IS
  'Learner-specific memory hook for a leech card, generated by generate-mnemonic.';
