INSERT INTO public.dialect_rules
  (dialect, category, rule, examples, priority, status, source, notes)
VALUES
('Yemeni', 'msa_substitutions',
 'Use the Yemeni interrogative, never the MSA one: وين for "where", ليش for "why", أيش for "what", منو for "who".',
 '{"good": [{"msa":"أين","dialect":"وين"},{"msa":"لماذا","dialect":"ليش"},{"msa":"ماذا","dialect":"أيش"},{"msa":"من هو","dialect":"منو"}], "bad": ["أين","لماذا","ماذا"]}',
 5, 'draft', 'corpus_mined',
 'Lisan counts: وين 316, ليش 775, أيش 1067, منو 45. فين (428) is commoner still but is Egyptian, borrowed through media — excluded deliberately.'),
('Yemeni', 'msa_substitutions',
 'Never negate with ليس. Yemeni uses مش or مو, or ما + pronoun (ما هو / ما هي).',
 '{"good": [{"msa":"ليس","dialect":"مش"},{"msa":"ليس","dialect":"مو"},{"msa":"ليس هو","dialect":"ما هو"}], "bad": ["ليس","ليست","لست"]}',
 5, 'draft', 'corpus_mined',
 'Lisan counts: مش 1326, مو 665, ما هو 221, ما هي 38, vs ليس 732. مش outranks مو 2:1; both are in real use, so the rule does not pick between them.'),
('Yemeni', 'msa_substitutions',
 'Use اللي as the relative pronoun for every gender and number. Never الذي / التي / الذين.',
 '{"good": [{"msa":"الذي","dialect":"اللي"},{"msa":"التي","dialect":"اللي"},{"msa":"الذين","dialect":"اللي"}], "bad": ["الذي","التي","الذين"]}',
 5, 'draft', 'corpus_mined',
 'Lisan counts: اللي 4406 vs الذي 2259, التي 1058, الذين 417 — the dialectal form outnumbers all three MSA forms combined.'),
('Yemeni', 'msa_substitutions',
 'For the plural demonstrative use ذول / هذول, not هؤلاء.',
 '{"good": [{"msa":"هؤلاء","dialect":"ذول"},{"msa":"هؤلاء","dialect":"هذول"}], "bad": ["هؤلاء"]}',
 3, 'draft', 'corpus_mined',
 'Lisan counts: هذول 50, ذول 21, ذولا 25, هولا 26 — 122 across variants vs هؤلاء 398. Lower confidence than the rules above; the MSA form still leads.'),
('Yemeni', 'msa_substitutions',
 'Say الحين or ذلحين for "now", not الآن.',
 '{"good": [{"msa":"الآن","dialect":"الحين"},{"msa":"الآن","dialect":"ذلحين"}], "bad": ["الآن"]}',
 4, 'draft', 'corpus_mined',
 'Lisan counts: الحين 418, ذلحين 58, ذحين 9. The seeded vocabulary rule leads with ذحين, which this corpus barely attests — worth a native-speaker check.'),
('Yemeni', 'pronoun',
 'The second person masculine plural is انتو (also انتوا), not انتم.',
 '{"good": [{"msa":"انتم","dialect":"انتو"}], "bad": ["انتم"]}',
 3, 'draft', 'corpus_mined',
 'Lisan counts: انتو 361, انتوا 63, vs انتم as lemma.'),
('Yemeni', 'negation',
 'Negate with ما before the verb. Do NOT use the Egyptian/Levantine ما...ش circumfix.',
 '{"good": ["ما عاد", "ما يحلو", "ما حسبنا"], "bad": ["مافيش","ماكانش","ماعنديش"]}',
 4, 'draft', 'corpus_mined',
 'Lisan affix inventory: bare ما negation prefix 5089 occurrences vs 131 for the ما...ش circumfix across all variants — a 39:1 ratio.');